# Generated by Django 6.0.6 on 2026-06-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descriptif', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('numero_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('numero_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sae_app.client')),
            ],
            options={
                'db_table': 'commande',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sae_app.categorie')),
            ],
            options={
                'db_table': 'produit',
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sae_app.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sae_app.produit')),
            ],
            options={
                'db_table': 'ligne_commande',
            },
        ),
    ]
